#!/bin/sh

exit_flag=0;

while [ $exit_flag -eq 0 ]
do
    read -p "Insert the command that install the package you want: " flatpak;

    flatpak="$flatpak -y";

    var=0;

    while [ $var -eq 0 ]
    do
        if $flatpak ; then
            var=1;
        else
            echo ">>>   Retrying...";
            var=0;
        fi
    done

    read -p "Do you wish to install another package?(y/n)" yn;

    case $yn in
            [Yy]* ) exit_flag=0;;
            [Nn]* ) exit_flag=1;;
            * ) echo "*** Please answer yes or no. ***";
    esac
done
